site_name: MkDocs Ubuntu Theme
site_name_short: Ubuntu Theme
site_url: http://organizer.ubucon.asia/
site_base_url: /
site_description: MkDocs Ubuntu Theme
site_author: Youngbin Han

repo_url: https://github.com/ubucon-asia/mkdocs-theme-ubuntu
repo_name: ubucon-asia/mkdocs-theme-ubuntu
contact_email: ybhan@ubuntu.com
copyright: Copyright &copy; 2023 Youngbin Han (ybhan at ubuntu.com)
edit_link_prefix: https://github.com/ubucon-asia/mkdocs-ubuntu/edit/main

theme:
    name: ubuntu

nav:
    - Home:
      - index.md
      - Submenu: 
        - markup.md

plugins:
    - search
